
package LOSPANELES;


import tpv.Acciones.AccionesProductos;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JTable;
import javax.swing.JTextField;
import tpv.principal.TpvFrame;

/**
 *  Clase PanelProductos
 * @author Ivan
 */
public class PanelProductos extends javax.swing.JPanel {
    //Variables de las clases importadas
    private TpvFrame frame;
    private AccionesProductos acciones;
    //Variables de la clase
    String imagenSeleccionada;
    
    /**
     * Constructor de la clase
     * @param frame 
     */
    public PanelProductos(TpvFrame frame) {
        this.frame = frame;
        initComponents();
        acciones = new AccionesProductos(this);  
        frame.setVisible(true);
        
    }

    /**
     * Metodos get y set de la clase
     */
    public TpvFrame getFrame() {
        return frame;
    }

    public void setFrame(TpvFrame frame) {
        this.frame = frame;
    }

    public AccionesProductos getAcciones() {
        return acciones;
    }

    public void setAcciones(AccionesProductos acciones) {
        this.acciones = acciones;
    }

    public JButton getBtnAtras() {
        return btnAtras;
    }

    public void setBtnAtras(JButton btnAtras) {
        this.btnAtras = btnAtras;
    }

    public JButton getjButton1() {
        return btnAdd;
    }

    public void setjButton1(JButton jButton1) {
        this.btnAdd = jButton1;
    }

    public JButton getjButton2() {
        return btnEliminar;
    }

    public void setjButton2(JButton jButton2) {
        this.btnEliminar = jButton2;
    }

    public JTextField getTxtAdd() {
        return txtAdd;
    }

    public void setTxtAdd(JTextField txtAdd) {
        this.txtAdd = txtAdd;
    }

    public JTextField getTxtEliminar() {
        return txtEliminar;
    }

    public void setTxtEliminar(JTextField txtEliminar) {
        this.txtEliminar = txtEliminar;
    }

    public JTable getTblProductos() {
        return tblProductos;
    }

    public void setTblProductos(JTable tblProductos) {
        this.tblProductos = tblProductos;
    }

    public JTextField getTxtCategoria() {
        return txtCategoria;
    }

    public void setTxtCategoria(String txtCategoria) {
        this.txtCategoria.setText(txtCategoria);
    }

    public JTextField getTxtPrecio() {
        return txtPrecio;
    }

    public void setTxtPrecio(JTextField txtPrecio) {
        this.txtPrecio = txtPrecio;
    }

    public JLabel getLblCategoriaSeleccionada() {
        return lblCategoriaSeleccionada;
    }

    public void setLblCategoriaSeleccionada(String lblCategoriaSeleccionada) {
        this.lblCategoriaSeleccionada.setText(lblCategoriaSeleccionada);
    }

    public JLabel getLblFoto1() {
        return lblFoto1;
    }

    public void setLblFoto1(JLabel lblFoto1) {
        this.lblFoto1 = lblFoto1;
    }

    public String getImagenSeleccionada() {
        return imagenSeleccionada;
    }

    public void setImagenSeleccionada(String imagenSeleccionada) {
        this.imagenSeleccionada = imagenSeleccionada;
    }
    
   
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtEliminar = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtAdd = new javax.swing.JTextField();
        btnAtras = new javax.swing.JButton();
        btnAdd = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        txtCategoria = new javax.swing.JTextField();
        btnSeleccionarCategoria = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        txtPrecio = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblProductos = new javax.swing.JTable();
        jLabel6 = new javax.swing.JLabel();
        lblCategoriaSeleccionada = new javax.swing.JLabel();
        lblFoto1 = new javax.swing.JLabel();
        lblFoto2 = new javax.swing.JLabel();
        lblFoto3 = new javax.swing.JLabel();
        lblFoto4 = new javax.swing.JLabel();
        lblFoto5 = new javax.swing.JLabel();
        lblFoto6 = new javax.swing.JLabel();
        lblFoto7 = new javax.swing.JLabel();
        lblFoto15 = new javax.swing.JLabel();
        lblFoto16 = new javax.swing.JLabel();
        lblFoto17 = new javax.swing.JLabel();
        lblFoto18 = new javax.swing.JLabel();
        lblFoto19 = new javax.swing.JLabel();
        lblFoto20 = new javax.swing.JLabel();
        lblFoto21 = new javax.swing.JLabel();

        setMaximumSize(new java.awt.Dimension(80, 80));
        setMinimumSize(new java.awt.Dimension(80, 80));
        setPreferredSize(new java.awt.Dimension(80, 80));

        txtEliminar.setHorizontalAlignment(javax.swing.JTextField.LEFT);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("Productos");

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Añadir nombre producto");

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Eliminar producto");

        txtAdd.setHorizontalAlignment(javax.swing.JTextField.LEFT);

        btnAtras.setText("<--");
        btnAtras.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAtrasMouseClicked(evt);
            }
        });

        btnAdd.setText("Añadir producto");
        btnAdd.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAddMouseClicked(evt);
            }
        });

        btnEliminar.setText("Eliminar");
        btnEliminar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnEliminarMouseClicked(evt);
            }
        });

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Selecciona categoria");

        txtCategoria.setHorizontalAlignment(javax.swing.JTextField.LEFT);

        btnSeleccionarCategoria.setText("Seleccionar");
        btnSeleccionarCategoria.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSeleccionarCategoriaMouseClicked(evt);
            }
        });

        jLabel5.setText("Añadir precio producto");

        tblProductos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Categoria", "Nombre Producto", "Precio Producto"
            }
        ));
        jScrollPane1.setViewportView(tblProductos);

        jLabel6.setText("Categoria seleccionada");

        lblFoto1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/agua.png"))); // NOI18N
        lblFoto1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        lblFoto1.setMaximumSize(new java.awt.Dimension(500, 500));
        lblFoto1.setMinimumSize(new java.awt.Dimension(80, 80));
        lblFoto1.setPreferredSize(new java.awt.Dimension(80, 80));
        lblFoto1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblFoto1MouseClicked(evt);
            }
        });

        lblFoto2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/refresco.png"))); // NOI18N
        lblFoto2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        lblFoto2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblFoto2MouseClicked(evt);
            }
        });

        lblFoto3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/bebida3.png"))); // NOI18N
        lblFoto3.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        lblFoto3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblFoto3MouseClicked(evt);
            }
        });

        lblFoto4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/bolleria1.png"))); // NOI18N
        lblFoto4.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        lblFoto4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblFoto4MouseClicked(evt);
            }
        });

        lblFoto5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/cafe1.png"))); // NOI18N
        lblFoto5.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        lblFoto5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblFoto5MouseClicked(evt);
            }
        });

        lblFoto6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/cafe2.png"))); // NOI18N
        lblFoto6.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        lblFoto6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblFoto6MouseClicked(evt);
            }
        });

        lblFoto7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/cafe3.png"))); // NOI18N
        lblFoto7.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        lblFoto7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblFoto7MouseClicked(evt);
            }
        });

        lblFoto15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/cerveza.png"))); // NOI18N
        lblFoto15.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        lblFoto15.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblFoto15MouseClicked(evt);
            }
        });

        lblFoto16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/coca-cola.png"))); // NOI18N
        lblFoto16.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        lblFoto16.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblFoto16MouseClicked(evt);
            }
        });

        lblFoto17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/coctel1.png"))); // NOI18N
        lblFoto17.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        lblFoto17.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblFoto17MouseClicked(evt);
            }
        });

        lblFoto18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/menu1.png"))); // NOI18N
        lblFoto18.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        lblFoto18.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblFoto18MouseClicked(evt);
            }
        });

        lblFoto19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/menu2.png"))); // NOI18N
        lblFoto19.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        lblFoto19.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblFoto19MouseClicked(evt);
            }
        });

        lblFoto20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/patatas.png"))); // NOI18N
        lblFoto20.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        lblFoto20.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblFoto20MouseClicked(evt);
            }
        });

        lblFoto21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/sandwich.png"))); // NOI18N
        lblFoto21.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        lblFoto21.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblFoto21MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(btnAtras)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel6)
                            .addComponent(jLabel2)
                            .addComponent(jLabel5))
                        .addGap(34, 34, 34)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblCategoriaSeleccionada, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, 306, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnSeleccionarCategoria))
                            .addComponent(txtAdd)
                            .addComponent(txtPrecio)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtEliminar)
                                .addGap(18, 18, 18)
                                .addComponent(btnEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(lblFoto15, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(lblFoto16, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(lblFoto17, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(lblFoto18, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(lblFoto19, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(lblFoto20, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(lblFoto1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(lblFoto2, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(lblFoto3, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(lblFoto4, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(lblFoto5, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(lblFoto6, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(lblFoto21, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lblFoto7)))
                            .addComponent(btnAdd, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jScrollPane1))))
                .addContainerGap(224, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(33, 33, 33)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(txtCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnSeleccionarCategoria))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel6)
                            .addComponent(lblCategoriaSeleccionada, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtAdd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addGap(55, 55, 55)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblFoto7)
                            .addComponent(lblFoto1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblFoto6)
                            .addComponent(lblFoto5)
                            .addComponent(lblFoto4)
                            .addComponent(lblFoto2)
                            .addComponent(lblFoto3))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblFoto15, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblFoto17, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblFoto18, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblFoto19, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblFoto20, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblFoto16, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblFoto21, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(btnAdd)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(btnEliminar)
                            .addComponent(txtEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(btnAtras))
                .addGap(27, 27, 27)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents
    
    /**
     * Botón que te lleva al menú principal
     * @param evt 
     */
    private void btnAtrasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAtrasMouseClicked
        frame.atras();
    }//GEN-LAST:event_btnAtrasMouseClicked
    
    /**
     * Boton que añade un producto a la base de datos y a la tabla
     * @param evt 
     */
    private void btnAddMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAddMouseClicked
        acciones.crearProducto();
        acciones.activaTabla();
        
    }//GEN-LAST:event_btnAddMouseClicked
    
    /**
     * Botón que elimina un producto de la base de datos y de la tabla
     * @param evt 
     */
    private void btnEliminarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEliminarMouseClicked
        acciones.eliminarProducto();
        acciones.activaTabla();
    }//GEN-LAST:event_btnEliminarMouseClicked
    /**
     * Boton para seleccionar la categoria en la que se guardaran los productos.
     * @param evt 
     */
    private void btnSeleccionarCategoriaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSeleccionarCategoriaMouseClicked
        acciones.seleccionarCategoria();
        setTxtCategoria("");
    }//GEN-LAST:event_btnSeleccionarCategoriaMouseClicked
    
    /**
     * Añade el numero 1 en la base de datos que mas tarde se relacionara con su respectiva imagen.
     * @param evt 
     */
    private void lblFoto1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblFoto1MouseClicked
        setImagenSeleccionada("1");
    }//GEN-LAST:event_lblFoto1MouseClicked
    /**
     * Añade el numero 2 en la base de datos que mas tarde se relacionara con su respectiva imagen.
     * @param evt 
     */
    private void lblFoto2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblFoto2MouseClicked
        setImagenSeleccionada("2");
    }//GEN-LAST:event_lblFoto2MouseClicked
    /**
     * Añade el numero 3 en la base de datos que mas tarde se relacionara con su respectiva imagen.
     * @param evt 
     */
    private void lblFoto3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblFoto3MouseClicked
        setImagenSeleccionada("3");
    }//GEN-LAST:event_lblFoto3MouseClicked
    /**
     * Añade el numero 4 en la base de datos que mas tarde se relacionara con su respectiva imagen.
     * @param evt 
     */
    private void lblFoto4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblFoto4MouseClicked
        setImagenSeleccionada("4");
    }//GEN-LAST:event_lblFoto4MouseClicked
    /**
     * Añade el numero 5 en la base de datos que mas tarde se relacionara con su respectiva imagen.
     * @param evt 
     */
    private void lblFoto5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblFoto5MouseClicked
        setImagenSeleccionada("5");
    }//GEN-LAST:event_lblFoto5MouseClicked
    /**
     * Añade el numero 6 en la base de datos que mas tarde se relacionara con su respectiva imagen.
     * @param evt 
     */
    private void lblFoto6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblFoto6MouseClicked
        setImagenSeleccionada("6");
    }//GEN-LAST:event_lblFoto6MouseClicked
    /**
     * Añade el numero 7 en la base de datos que mas tarde se relacionara con su respectiva imagen.
     * @param evt 
     */
    private void lblFoto7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblFoto7MouseClicked
        setImagenSeleccionada("7");
    }//GEN-LAST:event_lblFoto7MouseClicked
    /**
     * Añade el numero 8 en la base de datos que mas tarde se relacionara con su respectiva imagen.
     * @param evt 
     */
    private void lblFoto15MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblFoto15MouseClicked
        setImagenSeleccionada("8");
    }//GEN-LAST:event_lblFoto15MouseClicked
    /**
     * Añade el numero 9 en la base de datos que mas tarde se relacionara con su respectiva imagen.
     * @param evt 
     */
    private void lblFoto16MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblFoto16MouseClicked
        setImagenSeleccionada("9");
    }//GEN-LAST:event_lblFoto16MouseClicked
    /**
     * Añade el numero 10 en la base de datos que mas tarde se relacionara con su respectiva imagen.
     * @param evt 
     */
    private void lblFoto17MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblFoto17MouseClicked
        setImagenSeleccionada("10");
    }//GEN-LAST:event_lblFoto17MouseClicked
    /**
     * Añade el numero 11 en la base de datos que mas tarde se relacionara con su respectiva imagen.
     * @param evt 
     */
    private void lblFoto18MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblFoto18MouseClicked
        setImagenSeleccionada("11");
    }//GEN-LAST:event_lblFoto18MouseClicked
    /**
     * Añade el numero 12 en la base de datos que mas tarde se relacionara con su respectiva imagen.
     * @param evt 
     */
    private void lblFoto19MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblFoto19MouseClicked
        setImagenSeleccionada("12");
    }//GEN-LAST:event_lblFoto19MouseClicked
    /**
     * Añade el numero 13 en la base de datos que mas tarde se relacionara con su respectiva imagen.
     * @param evt 
     */
    private void lblFoto20MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblFoto20MouseClicked
        setImagenSeleccionada("13");
    }//GEN-LAST:event_lblFoto20MouseClicked
    /**
     * Añade el numero 14 en la base de datos que mas tarde se relacionara con su respectiva imagen.
     * @param evt 
     */
    private void lblFoto21MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblFoto21MouseClicked
        setImagenSeleccionada("14");
    }//GEN-LAST:event_lblFoto21MouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnAtras;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnSeleccionarCategoria;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblCategoriaSeleccionada;
    private javax.swing.JLabel lblFoto1;
    private javax.swing.JLabel lblFoto15;
    private javax.swing.JLabel lblFoto16;
    private javax.swing.JLabel lblFoto17;
    private javax.swing.JLabel lblFoto18;
    private javax.swing.JLabel lblFoto19;
    private javax.swing.JLabel lblFoto2;
    private javax.swing.JLabel lblFoto20;
    private javax.swing.JLabel lblFoto21;
    private javax.swing.JLabel lblFoto3;
    private javax.swing.JLabel lblFoto4;
    private javax.swing.JLabel lblFoto5;
    private javax.swing.JLabel lblFoto6;
    private javax.swing.JLabel lblFoto7;
    private javax.swing.JTable tblProductos;
    private javax.swing.JTextField txtAdd;
    private javax.swing.JTextField txtCategoria;
    private javax.swing.JTextField txtEliminar;
    private javax.swing.JTextField txtPrecio;
    // End of variables declaration//GEN-END:variables
}
