package LOSPANELES;

import Objetos.ServiceCliente;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JTable;
import javax.swing.JTextField;
import tpv.principal.TpvFrame;

/**
 *  Clase del panel Clientes
 * @author Ivan
 */
public class PanelClientes extends javax.swing.JPanel {
     //Variables de la clase
    private TpvFrame frame;
    private ServiceCliente service;
  
    /**
     * Constructor de la clase
     * @param frame 
     */
    public PanelClientes(TpvFrame frame) {
        this.frame = frame;
        initComponents();
        service = new ServiceCliente(this);
    }
    /**
     * Constructor para conectar con ServiceCliente
     * @param service 
     */
    public PanelClientes(ServiceCliente service) {
        this.service = service;
    }
    

    /**
     * Metodos get y set de los botones/labels/txtFields que se utilizan dinamicamente
     * @return 
     */
    public JButton getBtnAtras() {
        return btnAtras;
    }

    public void setBtnAtras(JButton btnAtras) {
        this.btnAtras = btnAtras;
    }

    public JTextField getTxtAdd() {
        return txtAdd;
    }

    public void setTxtAdd(String text) {
        txtAdd.setText(text);
    }

    public JTextField getTxtEliminarClave() {
        return txtEliminarClave;
    }

    public void setTxtEliminarClave(JTextField txtEliminarClave) {
        this.txtEliminarClave = txtEliminarClave;
    }

    public JTextField getTxtEliminarNombre() {
        return txtEliminarNombre;
    }

    public void setTxtEliminarNombre(JTextField txtEliminarNombre) {
        this.txtEliminarNombre = txtEliminarNombre;
    }
    

    public JTable getTblClientes() {
        return tblClientes;
    }

    public void setTblClientes(JTable tblClientes) {
        this.tblClientes = tblClientes;
    }

    public JLabel getLblContador() {
        return lblContador;
    }

    public void setLblContador(String text) {
        lblContador.setText(text);
    }

    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtEliminarNombre = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblClientes = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtAdd = new javax.swing.JTextField();
        btnAtras = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        txtEliminarClave = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        lblContador = new javax.swing.JLabel();

        setLayout(null);
        add(txtEliminarNombre);
        txtEliminarNombre.setBounds(120, 180, 290, 22);

        tblClientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Nombre", "Apellidos", "Clave"
            }
        ));
        jScrollPane1.setViewportView(tblClientes);

        add(jScrollPane1);
        jScrollPane1.setBounds(50, 280, 452, 168);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("Clientes");
        add(jLabel1);
        jLabel1.setBounds(211, 13, 95, 29);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel2.setText("Añadir");
        add(jLabel2);
        jLabel2.setBounds(120, 80, 50, 16);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel3.setText("Eliminar");
        add(jLabel3);
        jLabel3.setBounds(120, 150, 70, 16);
        add(txtAdd);
        txtAdd.setBounds(120, 110, 290, 22);

        btnAtras.setText("<--");
        btnAtras.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAtrasMouseClicked(evt);
            }
        });
        add(btnAtras);
        btnAtras.setBounds(12, 13, 60, 40);

        jLabel6.setText("Nombre");
        add(jLabel6);
        jLabel6.setBounds(50, 110, 50, 16);

        jButton1.setText("Añadir");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        add(jButton1);
        jButton1.setBounds(420, 110, 80, 25);

        btnEliminar.setText("Eliminar");
        btnEliminar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnEliminarMouseClicked(evt);
            }
        });
        add(btnEliminar);
        btnEliminar.setBounds(420, 210, 90, 25);
        add(txtEliminarClave);
        txtEliminarClave.setBounds(120, 210, 290, 22);

        jLabel5.setText("Nombre");
        add(jLabel5);
        jLabel5.setBounds(60, 180, 50, 16);

        jLabel7.setText("Clave");
        add(jLabel7);
        jLabel7.setBounds(60, 210, 31, 16);

        jLabel8.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        jLabel8.setText("Total clientes");
        add(jLabel8);
        jLabel8.setBounds(560, 30, 90, 20);

        jLabel9.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        jLabel9.setText("habituales");
        add(jLabel9);
        jLabel9.setBounds(570, 40, 80, 40);

        lblContador.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        lblContador.setForeground(new java.awt.Color(102, 153, 255));
        add(lblContador);
        lblContador.setBounds(580, 80, 50, 40);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Boton que te lleva al menu principal
     * @param evt 
     */
    private void btnAtrasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAtrasMouseClicked
        frame.atras();
    }//GEN-LAST:event_btnAtrasMouseClicked
    /**
     * Boton que guarda los datos del cliente y los introduce en la base de 
     * datos, en la tabla y añade el numero de clientes registrados en un label
     * @param evt 
     */
    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        service.saveCliente();
        service.activaTabla();
        service.contarClientes();
    }//GEN-LAST:event_jButton1MouseClicked
    /**
     * Boton que borra los registros de un cliente de la base de datos y 
     * actualiza la tabla y el contador.
     * @param evt 
     */
    private void btnEliminarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEliminarMouseClicked
        service.deleteCliente();
        service.activaTabla();
        service.contarClientes();
    }//GEN-LAST:event_btnEliminarMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAtras;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblContador;
    private javax.swing.JTable tblClientes;
    private javax.swing.JTextField txtAdd;
    private javax.swing.JTextField txtEliminarClave;
    private javax.swing.JTextField txtEliminarNombre;
    // End of variables declaration//GEN-END:variables
}
