
package LOSPANELES;

import javax.swing.JButton;
import javax.swing.JTable;
import javax.swing.JTextField;
import tpv.Acciones.AccionesCategorias;
import tpv.principal.TpvFrame;

/**
 * Clase PanelCategorias
 * @author Ivan
 */
public class PanelCategorias extends javax.swing.JPanel {
    //Variables de clases importadas 
    private TpvFrame frame;
    private AccionesCategorias acciones;
    //Variables para esta clase
    String imagenSeleccionada;
    /**
     * Constructor de la clase que activa componentes necesarios, conecta con la 
     * clase AccionesCategorias y activa la tabla.
     * @param frame 
     */

    public PanelCategorias(TpvFrame frame) {
        this.frame = frame;
        initComponents();
        acciones = new AccionesCategorias(this);
        acciones.activaTabla();
    }

    
    /**
     * Todos los metodods get y set
     */
    public TpvFrame getFrame() {
        return frame;
    }

    public void setFrame(TpvFrame frame) {
        this.frame = frame;
    }


    public JButton getBtnAdd() {
        return btnAdd;
    }

    public void setBtnAdd(JButton btnAdd) {
        this.btnAdd = btnAdd;
    }


    public JButton getBtnAtras() {
        return btnAtras;
    }

    public void setBtnAtras(JButton btnAtras) {
        this.btnAtras = btnAtras;
    }
  

    public JButton getBtnEliminar() {
        return btnEliminar;
    }

    public void setBtnEliminar(JButton btnEliminar) {
        this.btnEliminar = btnEliminar;
    }

    public JTextField getTxtAdd() {
        return txtAdd;
    }

    public void setTxtAdd(String txtAdd) {
        this.txtAdd.setText(txtAdd);
    }

    public JTextField getTxtEliminar() {
        return txtEliminar;
    }

    public void setTxtEliminar(String txtEliminar) {
        this.txtEliminar.setText(txtEliminar);
    }

    public JTable getTblCategorias() {
        return tblCategorias;
    }

    public void setTblCategorias(JTable tblCategorias) {
        this.tblCategorias = tblCategorias;
    }

    public String getImagenSeleccionada() {
        return imagenSeleccionada;
    }

    public void setImagenSeleccionada(String imagenSeleccionada) {
        this.imagenSeleccionada = imagenSeleccionada;
    }

    

    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtEliminar = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtAdd = new javax.swing.JTextField();
        btnAdd = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        btnAtras = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblCategorias = new javax.swing.JTable();
        lblFoto1 = new javax.swing.JLabel();
        lblFoto2 = new javax.swing.JLabel();
        lblFoto3 = new javax.swing.JLabel();
        lblFoto4 = new javax.swing.JLabel();
        lblFoto5 = new javax.swing.JLabel();
        lblFoto6 = new javax.swing.JLabel();
        lblFoto7 = new javax.swing.JLabel();
        lblFoto15 = new javax.swing.JLabel();
        lblFoto16 = new javax.swing.JLabel();
        lblFoto17 = new javax.swing.JLabel();
        lblFoto18 = new javax.swing.JLabel();
        lblFoto19 = new javax.swing.JLabel();
        lblFoto20 = new javax.swing.JLabel();
        lblFoto21 = new javax.swing.JLabel();

        setLayout(null);

        txtEliminar.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        add(txtEliminar);
        txtEliminar.setBounds(120, 370, 209, 22);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("Categorias");
        add(jLabel1);
        jLabel1.setBounds(120, 60, 127, 29);

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Añadir");
        add(jLabel2);
        jLabel2.setBounds(50, 120, 37, 16);

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Eliminar");
        add(jLabel3);
        jLabel3.setBounds(50, 370, 46, 16);

        txtAdd.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        add(txtAdd);
        txtAdd.setBounds(120, 120, 209, 22);

        btnAdd.setText("Añadir");
        btnAdd.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAddMouseClicked(evt);
            }
        });
        add(btnAdd);
        btnAdd.setBounds(350, 110, 79, 25);

        btnEliminar.setText("Eliminar");
        btnEliminar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnEliminarMouseClicked(evt);
            }
        });
        add(btnEliminar);
        btnEliminar.setBounds(350, 370, 79, 25);

        btnAtras.setText("<-");
        btnAtras.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAtrasMouseClicked(evt);
            }
        });
        add(btnAtras);
        btnAtras.setBounds(20, 14, 58, 42);

        tblCategorias.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null},
                {null},
                {null},
                {null}
            },
            new String [] {
                "Nombre categoria"
            }
        ));
        jScrollPane1.setViewportView(tblCategorias);

        add(jScrollPane1);
        jScrollPane1.setBounds(50, 420, 160, 120);

        lblFoto1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/agua.png"))); // NOI18N
        lblFoto1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        lblFoto1.setMaximumSize(new java.awt.Dimension(500, 500));
        lblFoto1.setMinimumSize(new java.awt.Dimension(80, 80));
        lblFoto1.setPreferredSize(new java.awt.Dimension(80, 80));
        lblFoto1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblFoto1MouseClicked(evt);
            }
        });
        add(lblFoto1);
        lblFoto1.setBounds(40, 160, 80, 80);

        lblFoto2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/refresco.png"))); // NOI18N
        lblFoto2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        lblFoto2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblFoto2MouseClicked(evt);
            }
        });
        add(lblFoto2);
        lblFoto2.setBounds(130, 160, 84, 84);

        lblFoto3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/bebida3.png"))); // NOI18N
        lblFoto3.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        lblFoto3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblFoto3MouseClicked(evt);
            }
        });
        add(lblFoto3);
        lblFoto3.setBounds(220, 160, 84, 84);

        lblFoto4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/bolleria1.png"))); // NOI18N
        lblFoto4.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        lblFoto4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblFoto4MouseClicked(evt);
            }
        });
        add(lblFoto4);
        lblFoto4.setBounds(310, 160, 84, 84);

        lblFoto5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/cafe1.png"))); // NOI18N
        lblFoto5.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        lblFoto5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblFoto5MouseClicked(evt);
            }
        });
        add(lblFoto5);
        lblFoto5.setBounds(400, 160, 84, 84);

        lblFoto6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/cafe2.png"))); // NOI18N
        lblFoto6.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        lblFoto6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblFoto6MouseClicked(evt);
            }
        });
        add(lblFoto6);
        lblFoto6.setBounds(490, 160, 84, 84);

        lblFoto7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/cafe3.png"))); // NOI18N
        lblFoto7.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        lblFoto7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblFoto7MouseClicked(evt);
            }
        });
        add(lblFoto7);
        lblFoto7.setBounds(580, 160, 84, 84);

        lblFoto15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/cerveza.png"))); // NOI18N
        lblFoto15.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        lblFoto15.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblFoto15MouseClicked(evt);
            }
        });
        add(lblFoto15);
        lblFoto15.setBounds(40, 250, 84, 84);

        lblFoto16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/coca-cola.png"))); // NOI18N
        lblFoto16.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        lblFoto16.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblFoto16MouseClicked(evt);
            }
        });
        add(lblFoto16);
        lblFoto16.setBounds(130, 250, 84, 84);

        lblFoto17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/coctel1.png"))); // NOI18N
        lblFoto17.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        lblFoto17.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblFoto17MouseClicked(evt);
            }
        });
        add(lblFoto17);
        lblFoto17.setBounds(220, 250, 84, 84);

        lblFoto18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/menu1.png"))); // NOI18N
        lblFoto18.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        lblFoto18.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblFoto18MouseClicked(evt);
            }
        });
        add(lblFoto18);
        lblFoto18.setBounds(310, 250, 84, 84);

        lblFoto19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/menu2.png"))); // NOI18N
        lblFoto19.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        lblFoto19.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblFoto19MouseClicked(evt);
            }
        });
        add(lblFoto19);
        lblFoto19.setBounds(400, 250, 84, 84);

        lblFoto20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/patatas.png"))); // NOI18N
        lblFoto20.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        lblFoto20.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblFoto20MouseClicked(evt);
            }
        });
        add(lblFoto20);
        lblFoto20.setBounds(490, 250, 84, 84);

        lblFoto21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/sandwich.png"))); // NOI18N
        lblFoto21.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        lblFoto21.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblFoto21MouseClicked(evt);
            }
        });
        add(lblFoto21);
        lblFoto21.setBounds(580, 250, 84, 84);
    }// </editor-fold>//GEN-END:initComponents
    
    /**
     * Vuelve al menu principal
     * @param evt 
     */
    private void btnAtrasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAtrasMouseClicked
        frame.atras();
    }//GEN-LAST:event_btnAtrasMouseClicked
    
    /**
     * Añade los datos introducidos en la base de datos y en la tabla
     * @param evt 
     */
    private void btnAddMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAddMouseClicked
        acciones.crearCategoria();
        acciones.activaTabla();
    }//GEN-LAST:event_btnAddMouseClicked
    /**
     * Elimina los datos introducidos de la base de datos y de la tabla
     * @param evt 
     */
    private void btnEliminarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEliminarMouseClicked
        acciones.eliminarCategoria();
        acciones.activaTabla();
    }//GEN-LAST:event_btnEliminarMouseClicked

    private void lblFoto1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblFoto1MouseClicked
        setImagenSeleccionada("1");
    }//GEN-LAST:event_lblFoto1MouseClicked

    private void lblFoto2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblFoto2MouseClicked
        setImagenSeleccionada("2");
    }//GEN-LAST:event_lblFoto2MouseClicked

    private void lblFoto3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblFoto3MouseClicked
        setImagenSeleccionada("3");
    }//GEN-LAST:event_lblFoto3MouseClicked

    private void lblFoto4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblFoto4MouseClicked
        setImagenSeleccionada("4");
    }//GEN-LAST:event_lblFoto4MouseClicked

    private void lblFoto5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblFoto5MouseClicked
        setImagenSeleccionada("5");
    }//GEN-LAST:event_lblFoto5MouseClicked

    private void lblFoto6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblFoto6MouseClicked
        setImagenSeleccionada("6");
    }//GEN-LAST:event_lblFoto6MouseClicked

    private void lblFoto7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblFoto7MouseClicked
        setImagenSeleccionada("7");
    }//GEN-LAST:event_lblFoto7MouseClicked

    private void lblFoto15MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblFoto15MouseClicked
        setImagenSeleccionada("8");
    }//GEN-LAST:event_lblFoto15MouseClicked

    private void lblFoto16MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblFoto16MouseClicked
        setImagenSeleccionada("9");
    }//GEN-LAST:event_lblFoto16MouseClicked

    private void lblFoto17MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblFoto17MouseClicked
        setImagenSeleccionada("10");
    }//GEN-LAST:event_lblFoto17MouseClicked

    private void lblFoto18MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblFoto18MouseClicked
        setImagenSeleccionada("11");
    }//GEN-LAST:event_lblFoto18MouseClicked

    private void lblFoto19MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblFoto19MouseClicked
        setImagenSeleccionada("12");
    }//GEN-LAST:event_lblFoto19MouseClicked

    private void lblFoto20MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblFoto20MouseClicked
        setImagenSeleccionada("13");
    }//GEN-LAST:event_lblFoto20MouseClicked

    private void lblFoto21MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblFoto21MouseClicked
        setImagenSeleccionada("14");
    }//GEN-LAST:event_lblFoto21MouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnAtras;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblFoto1;
    private javax.swing.JLabel lblFoto15;
    private javax.swing.JLabel lblFoto16;
    private javax.swing.JLabel lblFoto17;
    private javax.swing.JLabel lblFoto18;
    private javax.swing.JLabel lblFoto19;
    private javax.swing.JLabel lblFoto2;
    private javax.swing.JLabel lblFoto20;
    private javax.swing.JLabel lblFoto21;
    private javax.swing.JLabel lblFoto3;
    private javax.swing.JLabel lblFoto4;
    private javax.swing.JLabel lblFoto5;
    private javax.swing.JLabel lblFoto6;
    private javax.swing.JLabel lblFoto7;
    private javax.swing.JTable tblCategorias;
    private javax.swing.JTextField txtAdd;
    private javax.swing.JTextField txtEliminar;
    // End of variables declaration//GEN-END:variables
}
