
package tpv.principal;

import javax.swing.JPanel;
import LOSPANELES.PanelCajaRegistradora;
import LOSPANELES.PanelCategorias;
import LOSPANELES.PanelClientes;
import LOSPANELES.PanelEmpleados;
import LOSPANELES.PanelProductos;
import LOSPANELES.PanelTablaPedidos;

/**
 *  Frame del proyecto
 * @author Ivan
 */
public class TpvFrame extends javax.swing.JFrame {
    
    /**
     * Constructor de la clase
     */
    public TpvFrame() {
        initComponents();
        
    }
    
    
    /**
     * Método para volver al menú principal
     */
    public void atras(){
        addMenu();
    }
    /**
     * Método para vaciar el panelContenedor
     */
    public void contenedorVisible(){
        panelContenedor.removeAll();
        panelContenedor.setVisible(true);     
    }
    /**
     * Método para añadir el menú principal al panelContenedor
     */
    public void addMenu(){
        contenedorVisible();
        Menu panel = new Menu(this);
        panelContenedor.add(panel, java.awt.BorderLayout.CENTER);   
        pack();
    }
       
    /**
     * Método para añadir la cajaRegistradora al panelContenedor
     */
    public void cajaRegistradora(){
        contenedorVisible();
        PanelCajaRegistradora panel = new PanelCajaRegistradora(this);
        panelContenedor.add(panel, java.awt.BorderLayout.CENTER);        
        pack();
    }
    /**
     * Método para añadir el panel Categorias al panelContenedor
     */
    public void categorias(){
        contenedorVisible();
        PanelCategorias panel = new PanelCategorias(this);
        panelContenedor.add(panel, java.awt.BorderLayout.CENTER);        
        pack();
    }
    /**
     * Método para añadir el panel productos al panelContenedor
     */
    public void productos(){
        contenedorVisible();
        PanelProductos panel = new PanelProductos(this);
        panelContenedor.add(panel, java.awt.BorderLayout.CENTER);        
        pack();
    }
    /**
     * Método para añadir el panel clientes al panelContenedor
     */
    public void clientes(){
        contenedorVisible();
        PanelClientes panel = new PanelClientes(this);
        panelContenedor.add(panel, java.awt.BorderLayout.CENTER);        
        pack();
    }
    /**
     * Método para añadir el panelEmpleados al panelContenedor
     */
    public void empleados(){
        contenedorVisible();
        PanelEmpleados panel = new PanelEmpleados(this);
        panelContenedor.add(panel, java.awt.BorderLayout.CENTER);        
        pack();
    }
    
    /**
     * Método para añadir el panelTablaPedidos al panelContenedor
     */
    public void pedidos(){
        contenedorVisible();
        PanelTablaPedidos panel = new PanelTablaPedidos(this);
        panelContenedor.add(panel, java.awt.BorderLayout.CENTER);
        pack();
    }
    /**
     * Getter del panelContenedor
     * @return panelContenedor
     */
    public JPanel getPanelContenedor() {
        return panelContenedor;
    }
    /**
     * Setter del panelContenedor
     * @param panelContenedor 
     */
    public void setPanelContenedor(JPanel panelContenedor) {
        this.panelContenedor = panelContenedor;
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelContenedor = new javax.swing.JPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        mnuMenus = new javax.swing.JMenu();
        mnuCaja = new javax.swing.JMenuItem();
        mnuProductos = new javax.swing.JMenuItem();
        mnuClientes = new javax.swing.JMenuItem();
        mnuEmpleados = new javax.swing.JMenuItem();
        mnuOA = new javax.swing.JMenu();
        mnuSalir = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(153, 204, 255));
        setPreferredSize(new java.awt.Dimension(1000, 1000));

        panelContenedor.setMinimumSize(new java.awt.Dimension(500, 500));
        panelContenedor.setLayout(new java.awt.BorderLayout());

        mnuMenus.setText("Menús");

        mnuCaja.setText("Caja registradora");
        mnuCaja.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mnuCajaMouseClicked(evt);
            }
        });
        mnuCaja.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuCajaActionPerformed(evt);
            }
        });
        mnuMenus.add(mnuCaja);

        mnuProductos.setText("Productos");
        mnuProductos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mnuProductosMouseClicked(evt);
            }
        });
        mnuProductos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuProductosActionPerformed(evt);
            }
        });
        mnuMenus.add(mnuProductos);

        mnuClientes.setText("Clientes");
        mnuClientes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mnuClientesMouseClicked(evt);
            }
        });
        mnuClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuClientesActionPerformed(evt);
            }
        });
        mnuMenus.add(mnuClientes);

        mnuEmpleados.setText("Empleados");
        mnuEmpleados.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mnuEmpleadosMouseClicked(evt);
            }
        });
        mnuEmpleados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuEmpleadosActionPerformed(evt);
            }
        });
        mnuMenus.add(mnuEmpleados);

        jMenuBar1.add(mnuMenus);

        mnuOA.setText("Opciones avanzadas");

        mnuSalir.setText("Salir");
        mnuSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuSalirActionPerformed(evt);
            }
        });
        mnuOA.add(mnuSalir);

        jMenuBar1.add(mnuOA);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1400, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(panelContenedor, javax.swing.GroupLayout.PREFERRED_SIZE, 950, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1000, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(panelContenedor, javax.swing.GroupLayout.PREFERRED_SIZE, 950, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    /**
     * Utiliza el método cajaRegistradora
     * @param evt 
     */
    private void mnuCajaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mnuCajaMouseClicked
        cajaRegistradora();
    }//GEN-LAST:event_mnuCajaMouseClicked
    /**
     * Utiliza el método productos
     * @param evt 
     */
    private void mnuProductosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mnuProductosMouseClicked
        productos();
    }//GEN-LAST:event_mnuProductosMouseClicked
    /**
     * Utiliza el método clientes 
     * @param evt 
     */
    private void mnuClientesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mnuClientesMouseClicked
        clientes();
    }//GEN-LAST:event_mnuClientesMouseClicked
    /**
     * Utiliza el método empleados
     * @param evt 
     */
    private void mnuEmpleadosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mnuEmpleadosMouseClicked
        empleados();
    }//GEN-LAST:event_mnuEmpleadosMouseClicked
    /**
     * Utiliza el método  empleados
     * @param evt 
     */
    private void mnuEmpleadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuEmpleadosActionPerformed
        empleados();
    }//GEN-LAST:event_mnuEmpleadosActionPerformed
    /**
     * Utiliza el método cajaRegistradora
     * @param evt 
     */
    private void mnuCajaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuCajaActionPerformed
        cajaRegistradora();
    }//GEN-LAST:event_mnuCajaActionPerformed
    /**
     * Utiliza el método productos
     * @param evt 
     */
    private void mnuProductosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuProductosActionPerformed
        productos();
    }//GEN-LAST:event_mnuProductosActionPerformed
    /**
     * Utiliza el método clientes
     * @param evt 
     */
    private void mnuClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuClientesActionPerformed
        clientes();
    }//GEN-LAST:event_mnuClientesActionPerformed
    /**
     * Cierra el programa 
     * @param evt 
     */
    private void mnuSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuSalirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_mnuSalirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TpvFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TpvFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TpvFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TpvFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TpvFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem mnuCaja;
    private javax.swing.JMenuItem mnuClientes;
    private javax.swing.JMenuItem mnuEmpleados;
    private javax.swing.JMenu mnuMenus;
    private javax.swing.JMenu mnuOA;
    private javax.swing.JMenuItem mnuProductos;
    private javax.swing.JMenuItem mnuSalir;
    private javax.swing.JPanel panelContenedor;
    // End of variables declaration//GEN-END:variables
}
